version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  pre_build:
    commands:
      - npm run build

  build:
    commands:
      - aws s3 sync ./build/ s3://chandukani

artifacts:
  files: '**/*'
